language: php
php:
- 5.6
- 7.0
- 7.1
services:
- redis-server
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.6
    - python2.6-dev
    - nginx
    - realpath
    - lftp
env:
  global:
    - PLUGIN_NAME=CustomTrackerJs
    - PIWIK_ROOT_DIR=$TRAVIS_BUILD_DIR/piwik
    - PIWIK_REPOSITORY_SLUG=PiwikPRO/piwik.git
    - PIWIK_LATEST_STABLE_TEST_TARGET=3.x-pro
  matrix:
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL TEST_AGAINST_PIWIK_BRANCH=$PIWIK_LATEST_STABLE_TEST_TARGET

sudo: required
script: $PIWIK_ROOT_DIR/tests/travis/travis.sh
before_install:
  # do not use the Zend allocator on PHP 5.3 since it will randomly segfault after program execution
  - '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && export USE_ZEND_ALLOC=0 || true'

install:
- mkdir $PLUGIN_NAME
- cp -R !($PLUGIN_NAME) $PLUGIN_NAME
- cp -R .git/ $PLUGIN_NAME/
- cp .travis.yml $PLUGIN_NAME
- git clone -q https://$GITHUB_API_TOKEN:@github.com/$PIWIK_REPOSITORY_SLUG piwik
- cd piwik
- git fetch -q --all
- git submodule update
- '[ -d ./tests/travis/.git ] || sh -c "rm -rf ./tests/travis && git clone https://$GITHUB_API_TOKEN:@github.com/PiwikPRO/travis-scripts ./tests/travis"'
- cd ./tests/travis ; git checkout master ; cd ../..
- ./tests/travis/checkout_test_against_branch.sh
- '[ "$PLUGIN_NAME" == "" ] || [ ! -f ./tests/travis/check_plugin_compatible_with_piwik.php
  ] || php ./tests/travis/check_plugin_compatible_with_piwik.php "$PLUGIN_NAME"'
- ./tests/travis/configure_git.sh
- '[[ "$TRAVIS_PHP_VERSION" == 5.3* ]] && composer config -g -- disable-tls true ||
  true'
- '[ "$SKIP_COMPOSER_INSTALL" == "1" ] || travis_retry composer install'
- rm -rf plugins/$PLUGIN_NAME
- mv ../$PLUGIN_NAME plugins
- ./tests/travis/checkout_dependent_plugins.sh
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != 7* ]]; then phpenv config-rm xdebug.ini; fi

  # add always_populate_raw_post_data=-1 to php.ini
  - echo "always_populate_raw_post_data=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # disable opcache to avoid random failures on travis
  - echo "opcache.enable=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # make tmpfs and run MySQL on it for reasonnable performance
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
  - sudo start mysql

  # print out mysql information
  - mysql --version
  - mysql -e "SELECT VERSION();"

  # configure mysql
  - mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'" # Travis default
  # try to avoid 'mysql has gone away' errors
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 134209536;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"

  - mysql -e "SELECT @@sql_mode;"
  # - mysql -e "SHOW GLOBAL VARIABLES;"

  # print out more debugging info
  - uname -a
  - date
  - php -r "var_dump(gd_info());"
  - mysql -e 'create database piwik_tests;'

  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh

  - cd tests/PHPUnit

  # Hacks to make UI tests not fail
  - rm -rf ../../tmp/
  - sudo chmod -R 777 ../..
  - perl -i -0pe 's/(_construct\([\s\S].*\n.*{)/$1\n\t\t\$options\["cache"\] = false;/' $PIWIK_ROOT_DIR/vendor/twig/twig/lib/Twig/Environment.php

after_script:
  # change directory back to root travis dir
  - cd $PIWIK_ROOT_DIR

  # output contents of files w/ debugging info to screen
  - cat $PIWIK_ROOT_DIR/tests/travis/error.log
  - cat $PIWIK_ROOT_DIR/tmp/php-fpm.log
  - cat $PIWIK_ROOT_DIR/tmp/logs/piwik.log
  - cat $PIWIK_ROOT_DIR/config/config.ini.php

  # upload test artifacts (for debugging travis failures)
  - ./tests/travis/upload_artifacts.sh

after_success:
  - cd $PIWIK_ROOT_DIR
